# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
